### ISSUE TITLE
GPG 的正确使用姿势 | Mogeko`s Blog

### ISSUE THREAD

**Issue by Mogeko** [Mogeko/blog-commits#69]
https://mogeko.me/2019/068/ 

 Mogeko 的个人博客

**Comment by Sirice19** [comment]
请问文章第一段的黑幕文字是怎么实现的呢(๑•̀ㅁ•́ฅ

**Comment by Mogeko** [comment]
> @Sirice19
> 请问文章第一段的黑幕文字是怎么实现的呢(๑•̀ㅁ•́ฅ

这个很简单，用黑底黑子显示，然后在鼠标移上去的时候把字体变成白色

反映到CSS里就像这样
```css
.spoiler { 
  color: black; 
  background-color:black;
}
.spoiler:hover{
  color: white;
}
```
要用的时候用这个 HTML 标签把想隐藏的文字框起来就可以了
```html
<span class="spoiler" ></span>
```
